/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace LalalaEscrow {
  export type OrderStruct = {
    buyer: AddressLike;
    seller: AddressLike;
    amount: BigNumberish;
    createdAt: BigNumberish;
    status: BigNumberish;
  };

  export type OrderStructOutput = [
    buyer: string,
    seller: string,
    amount: bigint,
    createdAt: bigint,
    status: bigint
  ] & {
    buyer: string;
    seller: string;
    amount: bigint;
    createdAt: bigint;
    status: bigint;
  };
}

export interface LalalaEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "AUTO_RELEASE_PERIOD"
      | "FEE_BPS"
      | "autoRelease"
      | "autoReleaseAt"
      | "confirmDelivery"
      | "createOrder"
      | "feeRecipient"
      | "getOrder"
      | "orders"
      | "owner"
      | "raiseDispute"
      | "renounceOwnership"
      | "resolveDispute"
      | "setFeeRecipient"
      | "transferOwnership"
      | "usdt"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FeeRecipientUpdated"
      | "OrderAutoReleased"
      | "OrderCreated"
      | "OrderDisputed"
      | "OrderRefunded"
      | "OrderReleased"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "AUTO_RELEASE_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "FEE_BPS", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "autoRelease",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "autoReleaseAt",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmDelivery",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createOrder",
    values: [BytesLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "feeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getOrder", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "orders", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "raiseDispute",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeRecipient",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdt", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "AUTO_RELEASE_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "FEE_BPS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "autoRelease",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "autoReleaseAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confirmDelivery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOrder", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "orders", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "raiseDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdt", data: BytesLike): Result;
}

export namespace FeeRecipientUpdatedEvent {
  export type InputTuple = [newRecipient: AddressLike];
  export type OutputTuple = [newRecipient: string];
  export interface OutputObject {
    newRecipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderAutoReleasedEvent {
  export type InputTuple = [orderId: BytesLike];
  export type OutputTuple = [orderId: string];
  export interface OutputObject {
    orderId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderCreatedEvent {
  export type InputTuple = [
    orderId: BytesLike,
    buyer: AddressLike,
    seller: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    orderId: string,
    buyer: string,
    seller: string,
    amount: bigint
  ];
  export interface OutputObject {
    orderId: string;
    buyer: string;
    seller: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderDisputedEvent {
  export type InputTuple = [orderId: BytesLike, buyer: AddressLike];
  export type OutputTuple = [orderId: string, buyer: string];
  export interface OutputObject {
    orderId: string;
    buyer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderRefundedEvent {
  export type InputTuple = [orderId: BytesLike];
  export type OutputTuple = [orderId: string];
  export interface OutputObject {
    orderId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderReleasedEvent {
  export type InputTuple = [
    orderId: BytesLike,
    sellerAmount: BigNumberish,
    fee: BigNumberish
  ];
  export type OutputTuple = [
    orderId: string,
    sellerAmount: bigint,
    fee: bigint
  ];
  export interface OutputObject {
    orderId: string;
    sellerAmount: bigint;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LalalaEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): LalalaEscrow;
  waitForDeployment(): Promise<this>;

  interface: LalalaEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  AUTO_RELEASE_PERIOD: TypedContractMethod<[], [bigint], "view">;

  FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  autoRelease: TypedContractMethod<[orderId: BytesLike], [void], "nonpayable">;

  autoReleaseAt: TypedContractMethod<[orderId: BytesLike], [bigint], "view">;

  confirmDelivery: TypedContractMethod<
    [orderId: BytesLike],
    [void],
    "nonpayable"
  >;

  createOrder: TypedContractMethod<
    [orderId: BytesLike, seller: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  feeRecipient: TypedContractMethod<[], [string], "view">;

  getOrder: TypedContractMethod<
    [orderId: BytesLike],
    [LalalaEscrow.OrderStructOutput],
    "view"
  >;

  orders: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, bigint] & {
        buyer: string;
        seller: string;
        amount: bigint;
        createdAt: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  raiseDispute: TypedContractMethod<[orderId: BytesLike], [void], "nonpayable">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resolveDispute: TypedContractMethod<
    [orderId: BytesLike, refundBuyer: boolean],
    [void],
    "nonpayable"
  >;

  setFeeRecipient: TypedContractMethod<
    [newRecipient: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usdt: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "AUTO_RELEASE_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "autoRelease"
  ): TypedContractMethod<[orderId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "autoReleaseAt"
  ): TypedContractMethod<[orderId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "confirmDelivery"
  ): TypedContractMethod<[orderId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createOrder"
  ): TypedContractMethod<
    [orderId: BytesLike, seller: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "feeRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getOrder"
  ): TypedContractMethod<
    [orderId: BytesLike],
    [LalalaEscrow.OrderStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "orders"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, bigint] & {
        buyer: string;
        seller: string;
        amount: bigint;
        createdAt: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "raiseDispute"
  ): TypedContractMethod<[orderId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [orderId: BytesLike, refundBuyer: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setFeeRecipient"
  ): TypedContractMethod<[newRecipient: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdt"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "FeeRecipientUpdated"
  ): TypedContractEvent<
    FeeRecipientUpdatedEvent.InputTuple,
    FeeRecipientUpdatedEvent.OutputTuple,
    FeeRecipientUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OrderAutoReleased"
  ): TypedContractEvent<
    OrderAutoReleasedEvent.InputTuple,
    OrderAutoReleasedEvent.OutputTuple,
    OrderAutoReleasedEvent.OutputObject
  >;
  getEvent(
    key: "OrderCreated"
  ): TypedContractEvent<
    OrderCreatedEvent.InputTuple,
    OrderCreatedEvent.OutputTuple,
    OrderCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OrderDisputed"
  ): TypedContractEvent<
    OrderDisputedEvent.InputTuple,
    OrderDisputedEvent.OutputTuple,
    OrderDisputedEvent.OutputObject
  >;
  getEvent(
    key: "OrderRefunded"
  ): TypedContractEvent<
    OrderRefundedEvent.InputTuple,
    OrderRefundedEvent.OutputTuple,
    OrderRefundedEvent.OutputObject
  >;
  getEvent(
    key: "OrderReleased"
  ): TypedContractEvent<
    OrderReleasedEvent.InputTuple,
    OrderReleasedEvent.OutputTuple,
    OrderReleasedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "FeeRecipientUpdated(address)": TypedContractEvent<
      FeeRecipientUpdatedEvent.InputTuple,
      FeeRecipientUpdatedEvent.OutputTuple,
      FeeRecipientUpdatedEvent.OutputObject
    >;
    FeeRecipientUpdated: TypedContractEvent<
      FeeRecipientUpdatedEvent.InputTuple,
      FeeRecipientUpdatedEvent.OutputTuple,
      FeeRecipientUpdatedEvent.OutputObject
    >;

    "OrderAutoReleased(bytes32)": TypedContractEvent<
      OrderAutoReleasedEvent.InputTuple,
      OrderAutoReleasedEvent.OutputTuple,
      OrderAutoReleasedEvent.OutputObject
    >;
    OrderAutoReleased: TypedContractEvent<
      OrderAutoReleasedEvent.InputTuple,
      OrderAutoReleasedEvent.OutputTuple,
      OrderAutoReleasedEvent.OutputObject
    >;

    "OrderCreated(bytes32,address,address,uint256)": TypedContractEvent<
      OrderCreatedEvent.InputTuple,
      OrderCreatedEvent.OutputTuple,
      OrderCreatedEvent.OutputObject
    >;
    OrderCreated: TypedContractEvent<
      OrderCreatedEvent.InputTuple,
      OrderCreatedEvent.OutputTuple,
      OrderCreatedEvent.OutputObject
    >;

    "OrderDisputed(bytes32,address)": TypedContractEvent<
      OrderDisputedEvent.InputTuple,
      OrderDisputedEvent.OutputTuple,
      OrderDisputedEvent.OutputObject
    >;
    OrderDisputed: TypedContractEvent<
      OrderDisputedEvent.InputTuple,
      OrderDisputedEvent.OutputTuple,
      OrderDisputedEvent.OutputObject
    >;

    "OrderRefunded(bytes32)": TypedContractEvent<
      OrderRefundedEvent.InputTuple,
      OrderRefundedEvent.OutputTuple,
      OrderRefundedEvent.OutputObject
    >;
    OrderRefunded: TypedContractEvent<
      OrderRefundedEvent.InputTuple,
      OrderRefundedEvent.OutputTuple,
      OrderRefundedEvent.OutputObject
    >;

    "OrderReleased(bytes32,uint256,uint256)": TypedContractEvent<
      OrderReleasedEvent.InputTuple,
      OrderReleasedEvent.OutputTuple,
      OrderReleasedEvent.OutputObject
    >;
    OrderReleased: TypedContractEvent<
      OrderReleasedEvent.InputTuple,
      OrderReleasedEvent.OutputTuple,
      OrderReleasedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
